
framework:
  name: Network Validation Framework
  version: "1.0"
  author: Shravana Malawade

active_device: device1

devices:
  device1:
    board: Raspberry Pi 3 
    host: 192.168.31.35
    username: pi3
    password: raspberrypi

  device2:
    board: Raspberry Pi 3
    host: 192.168.31.36
    username: raspberrypi-2@
    password: raspberrypi

validation:
  layer1: true
  layer2: true
  layer3: true
  layer4: true
  application: true

reports:
  html: true
  csv: true
  json: true

logging:
  path: logs/framework.log
  level: INFO
