"""
Layer 1 Interface Validation Module

Validates whether a network interface exists
and is in UP state.
"""

from core.command import execute_command
from core.result import generate_result


def validate_interface(ssh, test_case, logger):
    """
    Validate network interface status.

    Args:
        ssh:
            Active SSH connection object.

        test_case:
            Test case details loaded from YAML.

        logger:
            Logger object.

    Returns:
        dict:
            Validation result generated by result.py.
    """

    # Get command from test case YAML
    command = test_case["command"]


    # Execute command on DUT using command executor
    output = execute_command(
        ssh,
        command,
        logger
    )


    # Check command execution result
    if output is None:

        return generate_result(
            test_case,
            "FAIL",
            "Command execution failed"
        )


    # Analyze command output
    lines = output.splitlines()


    # Check every line for active interface
    for line in lines:

        # Ignore loopback interface
        if "lo:" in line:
            continue


        # Check whether interface is UP
        if "UP" in line:

            return generate_result(
                test_case,
                "PASS",
                "Network interface is UP"
            )


    # No active interface found
    return generate_result(
        test_case,
        "FAIL",
        "No active network interface found"
    )
