"""
Layer 1 Link Validation Module

Validates physical carrier status
on the active wired Ethernet interface.
"""

from core.command import execute_command
from core.result import generate_result


def validate_link(ssh, test_case, logger):
    """
    Validate physical link carrier status.

    Args:
        ssh:
            Active SSH connection object.

        test_case:
            Test case details loaded from YAML.

        logger:
            Logger object.

    Returns:
        dict:
            Validation result generated by result.py.
    """

    command = test_case["command"]

    output = execute_command(
        ssh,
        command,
        logger
    )

    if output is None:

        return generate_result(
            test_case,
            "FAIL",
            "Command execution failed"
        )

    if output == "":

        return generate_result(
            test_case,
            "FAIL",
            "No active wired Ethernet interface found"
        )

    interface, carrier = output.rsplit(":", 1)

    expected_carrier = str(
        test_case["expected"]["carrier"]
    )

    if carrier == expected_carrier:

        return generate_result(
            test_case,
            "PASS",
            f"Physical link detected on interface: {interface}"
        )

    return generate_result(
        test_case,
        "FAIL",
        f"No physical link detected on interface: {interface}"
    )
